//! Golden-oracle test: runs this crate's parsers over every fixture under
//! `fixtures/inputs/{porcelain,diff}/` and asserts the canonical JSON
//! rendering is byte-identical to the corresponding file under
//! `fixtures/expected/{porcelain,diff}/`, which was generated by feeding the
//! *same* fixture files through the real Swift parsers
//! (`Sources/LaboLaboEngine/Git/{PorcelainStatusParser,UnifiedDiffParser}.swift`).
//! See `../README.md` for exactly how `fixtures/expected/**` was produced
//! and how to regenerate it after a fixture or schema change.
//!
//! Canonicalization here must match `fixtures/generate.swift`'s hand-rolled
//! JSON encoder exactly:
//!   - Compact form (no inserted whitespace).
//!   - Object keys sorted lexicographically. `serde_json::to_string` on a
//!     struct serializes fields in *declaration order* (it does not route
//!     through `serde_json::Value`'s `BTreeMap`, so nothing sorts for us
//!     automatically) -- so every `*View` struct below has its fields
//!     declared in the exact alphabetical order of their JSON key names.
//!     Do not reorder them without re-checking this.
//!   - `#[serde(skip_serializing_if = "Option::is_none")]` on every optional
//!     field, so `None` omits the key rather than emitting `null` (mirrors
//!     Swift's synthesized `encodeIfPresent` behavior for `Optional` stored
//!     properties).

use labolabo_core::{porcelain, unified_diff};
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};

// MARK: - Serializable views mirroring fixtures/generate.swift's JSON shape.
//
// These are intentionally separate from the production `git_models` /
// `unified_diff` types (which carry zero JSON/serde dependency in the
// library itself) and duplicate the "kind"/"change" string spellings and
// computed (additions/deletions/displayPath/isDetached/isDirty/...) fields
// the Swift generator emits, so the two sides can be compared byte-for-byte.

// Field order below is alphabetical by JSON key name (ahead, behind,
// branch, conflicted, entries, headSha, isDetached, isDirty, staged,
// unstaged, untracked, upstream) -- see module doc comment.
#[derive(Serialize)]
struct StatusView {
    ahead: i64,
    behind: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    branch: Option<String>,
    conflicted: Vec<String>,
    entries: Vec<EntryView>,
    #[serde(skip_serializing_if = "Option::is_none", rename = "headSha")]
    head_sha: Option<String>,
    #[serde(rename = "isDetached")]
    is_detached: bool,
    #[serde(rename = "isDirty")]
    is_dirty: bool,
    staged: Vec<String>,
    unstaged: Vec<String>,
    untracked: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    upstream: Option<String>,
}

// Field order: index, kind, originalPath, path, score, worktree.
#[derive(Serialize)]
struct EntryView {
    index: String,
    kind: String,
    #[serde(skip_serializing_if = "Option::is_none", rename = "originalPath")]
    original_path: Option<String>,
    path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    score: Option<i64>,
    worktree: String,
}

fn change_str(c: labolabo_core::Change) -> String {
    c.to_porcelain().to_string()
}

fn kind_str(k: labolabo_core::Kind) -> &'static str {
    use labolabo_core::Kind::*;
    match k {
        Ordinary => "ordinary",
        RenamedOrCopied => "renamedOrCopied",
        Unmerged => "unmerged",
        Untracked => "untracked",
        Ignored => "ignored",
    }
}

fn status_view(status: &labolabo_core::GitStatus) -> StatusView {
    StatusView {
        ahead: status.ahead,
        behind: status.behind,
        conflicted: status.conflicted().iter().map(|e| e.path.clone()).collect(),
        entries: status
            .entries
            .iter()
            .map(|e| EntryView {
                index: change_str(e.index),
                kind: kind_str(e.kind).to_string(),
                path: e.path.clone(),
                worktree: change_str(e.worktree),
                original_path: e.original_path.clone(),
                score: e.score,
            })
            .collect(),
        is_detached: status.is_detached(),
        is_dirty: status.is_dirty(),
        staged: status.staged().iter().map(|e| e.path.clone()).collect(),
        unstaged: status.unstaged().iter().map(|e| e.path.clone()).collect(),
        untracked: status.untracked().iter().map(|e| e.path.clone()).collect(),
        head_sha: status.head_sha.clone(),
        branch: status.branch.clone(),
        upstream: status.upstream.clone(),
    }
}

#[derive(Serialize)]
struct FileDiffView {
    additions: i64,
    deletions: i64,
    #[serde(rename = "displayPath")]
    display_path: String,
    hunks: Vec<HunkView>,
    #[serde(rename = "isBinary")]
    is_binary: bool,
    #[serde(rename = "isDeleted")]
    is_deleted: bool,
    #[serde(rename = "isNew")]
    is_new: bool,
    #[serde(rename = "isRename")]
    is_rename: bool,
    #[serde(skip_serializing_if = "Option::is_none", rename = "newPath")]
    new_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", rename = "oldPath")]
    old_path: Option<String>,
}

#[derive(Serialize)]
struct HunkView {
    header: String,
    lines: Vec<LineView>,
    #[serde(rename = "newCount")]
    new_count: i64,
    #[serde(rename = "newStart")]
    new_start: i64,
    #[serde(rename = "oldCount")]
    old_count: i64,
    #[serde(rename = "oldStart")]
    old_start: i64,
}

#[derive(Serialize)]
struct LineView {
    kind: String,
    #[serde(skip_serializing_if = "Option::is_none", rename = "newLineNumber")]
    new_line_number: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none", rename = "oldLineNumber")]
    old_line_number: Option<i64>,
    text: String,
}

fn line_kind_str(k: labolabo_core::LineKind) -> &'static str {
    use labolabo_core::LineKind::*;
    match k {
        Context => "context",
        Addition => "addition",
        Deletion => "deletion",
        NoNewline => "noNewline",
    }
}

fn file_diff_view(f: &labolabo_core::FileDiff) -> FileDiffView {
    FileDiffView {
        additions: f.additions(),
        deletions: f.deletions(),
        display_path: f.display_path().to_string(),
        hunks: f
            .hunks
            .iter()
            .map(|h| HunkView {
                header: h.header.clone(),
                lines: h
                    .lines
                    .iter()
                    .map(|l| LineView {
                        kind: line_kind_str(l.kind).to_string(),
                        new_line_number: l.new_line_number,
                        old_line_number: l.old_line_number,
                        text: l.text.clone(),
                    })
                    .collect(),
                new_count: h.new_count,
                new_start: h.new_start,
                old_count: h.old_count,
                old_start: h.old_start,
            })
            .collect(),
        is_binary: f.is_binary,
        is_deleted: f.is_deleted,
        is_new: f.is_new,
        is_rename: f.is_rename,
        new_path: f.new_path.clone(),
        old_path: f.old_path.clone(),
    }
}

// MARK: - Driver

fn fixtures_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures")
}

fn read_raw(path: &Path) -> String {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    String::from_utf8(bytes)
        .unwrap_or_else(|e| panic!("fixture {} is not valid UTF-8: {e}", path.display()))
}

fn assert_matches_golden(
    input_dir: &str,
    expected_dir: &str,
    parse: impl Fn(&str) -> String,
) -> usize {
    let inputs = fixtures_root().join("inputs").join(input_dir);
    let expected = fixtures_root().join("expected").join(expected_dir);

    let mut entries: Vec<PathBuf> = fs::read_dir(&inputs)
        .unwrap_or_else(|e| panic!("failed to read dir {}: {e}", inputs.display()))
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) != Some("json"))
        .collect();
    entries.sort();
    assert!(
        !entries.is_empty(),
        "no fixtures found under {}",
        inputs.display()
    );

    for input_path in &entries {
        let stem = input_path.file_stem().unwrap().to_str().unwrap();
        let expected_path = expected.join(format!("{stem}.json"));
        let raw = read_raw(input_path);
        let actual_json = parse(&raw);
        let expected_json = read_raw(&expected_path);
        assert_eq!(
            actual_json,
            expected_json,
            "\nmismatch for fixture `{stem}`\n  input:    {}\n  expected: {}",
            input_path.display(),
            expected_path.display(),
        );
    }
    entries.len()
}

#[test]
fn porcelain_status_matches_swift_oracle() {
    let n = assert_matches_golden("porcelain", "porcelain", |raw| {
        let status = porcelain::parse(raw);
        serde_json::to_string(&status_view(&status)).expect("serialize StatusView")
    });
    eprintln!("golden: {n} porcelain fixtures matched byte-for-byte");
}

#[test]
fn unified_diff_matches_swift_oracle() {
    let n = assert_matches_golden("diff", "diff", |raw| {
        let files = unified_diff::parse(raw);
        let views: Vec<FileDiffView> = files.iter().map(file_diff_view).collect();
        serde_json::to_string(&views).expect("serialize FileDiffView list")
    });
    eprintln!("golden: {n} diff fixtures matched byte-for-byte");
}
