//! Golden-oracle test for `labolabo_core::store`: opens a fixture SQLite
//! database that was **actually written by GRDB** (via the real
//! `LaboLaboStore.SessionDatabase`, not hand-authored) and exercises every
//! `SessionPersisting` operation against it, asserting the read results
//! match what was written and that a subsequent write round-trips through
//! `sqlite3` in GRDB's exact on-disk format.
//!
//! Unlike `tests/golden.rs`/`tests/tiling_golden.rs` (which compare
//! canonical JSON renderings against a byte-identical Swift-produced
//! expected file), this crate's operations here are database reads/writes,
//! not a pure function of a string -> JSON. So "golden" here means: the
//! fixture *file* is the oracle output (produced once by real GRDB), and
//! this test's hardcoded expected values are what a human verified that
//! fixture contains (via `sqlite3 fixture.db` — see the dump in this file's
//! comments below each assertion). There is no Rust-side regeneration step
//! for the fixture: it is regenerated by rerunning the Swift oracle
//! described next, not by anything in this repo.
//!
//! ## Fixture provenance / regenerating `fixtures/store/fixture.db`
//!
//! `fixtures/store/fixture.db` was produced by a disposable Swift package
//! (not checked in anywhere, per the porting brief's "leave no trace"
//! convention already used by `fixtures/generate.swift` and the wave-3
//! tiling driver) that depends on this repo's real `LaboLaboStore` product
//! (GRDB) via a local SwiftPM path dependency, and calls the real
//! `SessionDatabase.init(url:)` / `.upsert` / `.setSelectedSessionID` /
//! `.setAppState` — i.e. the exact code path a running LaboLabo app uses.
//! To regenerate:
//!
//! ```sh
//! mkdir -p /tmp/store-fixture-gen/Sources/store-fixture-gen
//! cat > /tmp/store-fixture-gen/Package.swift <<'EOF'
//! // swift-tools-version: 6.0
//! import PackageDescription
//! let package = Package(
//!     name: "store-fixture-gen",
//!     platforms: [.macOS(.v14)],
//!     dependencies: [.package(path: "/path/to/labolabo")],  // this repo's root
//!     targets: [.executableTarget(
//!         name: "store-fixture-gen",
//!         // "package:" must match the *directory basename* of the path
//!         // dependency above, not the `Package(name:)` declared inside it
//!         // (SwiftPM resolves local path dependency identity from the
//!         // directory name) -- e.g. "labolabo" for a `~/.../labolabo` checkout.
//!         dependencies: [.product(name: "LaboLaboStore", package: "<dir-basename>")]
//!     )]
//! )
//! EOF
//! # ... write Sources/store-fixture-gen/main.swift building the records
//! # below via SessionRecord(...)/db.upsert/db.setSelectedSessionID/db.setAppState ...
//! cd /tmp/store-fixture-gen && swift run store-fixture-gen \
//!   /path/to/labolabo/rust/crates/labolabo-core/fixtures/store/fixture.db
//! ```
//!
//! The fixture's exact contents (verified via `sqlite3 fixture.db
//! '.schema'` / `SELECT * FROM session` / `SELECT key, value,
//! typeof(value) FROM appState` / `SELECT * FROM grdb_migrations`):
//!
//! - `grdb_migrations`: exactly `v1`, `v2-agentSession`, `v3-adapter` (GRDB
//!   wrote this; this crate must never touch it).
//! - `session`: 4 rows (see `expected_sessions` below) — one fully
//!   populated with Japanese text, one with every optional column NULL, one
//!   with quotes/backslash/newline/tab/emoji content (parameter-binding
//!   correctness, not string interpolation), one with an exact-midnight
//!   `addedAt`. Inserted out of `sortOrder` order, to exercise `ORDER BY`.
//! - `appState`: `selectedSession` -> the first session's id; three
//!   `tab.pane.layout.*`-prefixed entries (one of them an **empty string**,
//!   which must be kept, distinct from...) a fourth `tab.pane.layout.*` key
//!   whose `value` is SQL **NULL** (which `app_state_entries` must drop);
//!   and one `other.unrelated.key` outside the prefix.

use std::path::{Path, PathBuf};

use chrono::{TimeZone, Utc};
use labolabo_core::store::{SessionDatabase, SessionPersisting, SessionRecord};

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/store/fixture.db")
}

/// Copies the checked-in fixture to a scratch path so tests that write
/// (`upsert`/`delete_session`/`set_app_state`) never mutate the committed
/// fixture file, and don't stomp on each other when tests run in parallel.
fn open_fixture_copy(test_name: &str) -> (SessionDatabase, PathBuf) {
    let dir = std::env::temp_dir().join(format!(
        "labolabo-store-golden-{}-{}",
        std::process::id(),
        test_name
    ));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("fixture.db");
    std::fs::copy(fixture_path(), &path).unwrap();
    let db = SessionDatabase::open(&path).unwrap();
    (db, path)
}

fn utc(y: i32, mo: u32, d: u32, h: u32, mi: u32, s: u32, ms: u32) -> chrono::DateTime<Utc> {
    Utc.with_ymd_and_hms(y, mo, d, h, mi, s).unwrap()
        + chrono::TimeDelta::milliseconds(i64::from(ms))
}

/// Expected `session` rows, in `sortOrder` order (0, 1, 2, 3) -- see this
/// file's module doc comment for the raw `sqlite3` dump this was
/// transcribed from.
fn expected_sessions() -> Vec<SessionRecord> {
    vec![
        SessionRecord::new(
            "11111111-1111-1111-1111-111111111111",
            "/Users/sasapiyo/repo/labolabo",
            "メイン作業ブランチ",
            Some("feature/店舗検索#42".to_string()),
            utc(2026, 7, 1, 9, 0, 0, 0),
            0,
            Some("agent-aaa-111".to_string()),
            Some("/Users/sasapiyo/.claude/projects/labolabo/agent-aaa-111.jsonl".to_string()),
            Some("claude".to_string()),
        ),
        SessionRecord::new(
            "33333333-3333-3333-3333-333333333333",
            "/tmp/repo's \"quoted\" path/with\nnewline",
            "Codex セッション/絵文字🚀テスト & <tags> \"quotes\" 'apostrophe' back\\slash",
            Some("dev".to_string()),
            utc(2025, 12, 31, 0, 0, 0, 5),
            1,
            Some("codex-session-999".to_string()),
            Some("/tmp/transcripts/codex\ttest.jsonl".to_string()),
            Some("codex".to_string()),
        ),
        SessionRecord::new(
            "22222222-2222-2222-2222-222222222222",
            "/Users/sasapiyo/repo/labolabo-worktree",
            "テスト用ワークツリー",
            None,
            utc(2026, 7, 2, 23, 59, 59, 999),
            2,
            None,
            None,
            None,
        ),
        SessionRecord::new(
            "44444444-4444-4444-4444-444444444444",
            "/Users/sasapiyo/repo/gemini-worktree",
            "Gemini セッション",
            Some("main".to_string()),
            utc(2026, 1, 1, 0, 0, 0, 0),
            3,
            None,
            None,
            Some("gemini".to_string()),
        ),
    ]
}

#[test]
fn all_sessions_matches_fixture_ordered_by_sort_order() {
    let (db, _dir) = open_fixture_copy("all_sessions");
    assert_eq!(db.all_sessions().unwrap(), expected_sessions());
}

#[test]
fn selected_session_id_matches_fixture() {
    let (db, _dir) = open_fixture_copy("selected_session_id");
    assert_eq!(
        db.selected_session_id().unwrap(),
        Some("11111111-1111-1111-1111-111111111111".to_string())
    );
}

#[test]
fn app_state_entries_drops_the_real_grdb_written_null_row() {
    let (db, _dir) = open_fixture_copy("app_state_entries");
    let entries = db.app_state_entries("tab.pane.layout.").unwrap();
    assert_eq!(
        entries.len(),
        3,
        "the NULL-valued tab.pane.layout.33333333... row must be dropped, not the other 3"
    );
    assert_eq!(
        entries.get("tab.pane.layout.11111111-1111-1111-1111-111111111111"),
        Some(&"{\"paneKind\":\"terminal\",\"paneTitle\":\"端末\"}".to_string())
    );
    assert_eq!(
        entries.get("tab.pane.layout.22222222-2222-2222-2222-222222222222"),
        Some(&"{\"paneKind\":\"terminal\",\"paneTitle\":\"記号!@#$%^&*()_+-=\"}".to_string())
    );
    // Empty string is a real value, distinct from the dropped NULL row.
    assert_eq!(
        entries.get("tab.pane.layout.empty-string"),
        Some(&String::new())
    );
    assert_eq!(
        entries.get("tab.pane.layout.33333333-3333-3333-3333-333333333333"),
        None
    );
    // Outside the prefix -- must not leak in.
    assert!(!entries.contains_key("other.unrelated.key"));
}

#[test]
fn app_state_on_a_real_null_valued_key_is_none_not_the_key_missing() {
    let (db, _dir) = open_fixture_copy("app_state_null");
    // The key exists (GRDB wrote a row for it with value = NULL); fetching
    // it must still report None, matching GRDB's fetchOne NULL-collapsing.
    assert_eq!(
        db.app_state("tab.pane.layout.33333333-3333-3333-3333-333333333333")
            .unwrap(),
        None
    );
    assert_eq!(
        db.app_state("other.unrelated.key").unwrap(),
        Some("unrelated-value".to_string())
    );
    assert_eq!(db.app_state("no-such-key-at-all").unwrap(), None);
}

#[test]
fn never_touches_grdb_migrations_across_a_full_read_write_delete_cycle() {
    let (db, path) = open_fixture_copy("grdb_migrations_untouched");

    let before = raw_grdb_migrations(&path);
    assert_eq!(before, vec!["v1", "v2-agentSession", "v3-adapter"]);

    // Exercise every write operation, not just reads.
    db.upsert(&SessionRecord::new(
        "55555555-5555-5555-5555-555555555555",
        "/tmp/new",
        "new session",
        None,
        utc(2027, 3, 4, 5, 6, 7, 42),
        4,
        None,
        None,
        None,
    ))
    .unwrap();
    db.delete_session("44444444-4444-4444-4444-444444444444")
        .unwrap();
    db.set_app_state(Some("v"), "some.new.key").unwrap();
    db.set_selected_session_id(Some("55555555-5555-5555-5555-555555555555"))
        .unwrap();
    drop(db);

    let after = raw_grdb_migrations(&path);
    assert_eq!(
        before, after,
        "grdb_migrations must be byte-identical before/after"
    );
}

#[test]
fn upsert_writes_grdb_exact_date_format_and_round_trips() {
    let (db, path) = open_fixture_copy("upsert_date_format");
    let record = SessionRecord::new(
        "66666666-6666-6666-6666-666666666666",
        "/tmp/six",
        "six",
        None,
        utc(2027, 3, 4, 5, 6, 7, 42),
        99,
        None,
        None,
        None,
    );
    db.upsert(&record).unwrap();
    drop(db);

    // Read the raw TEXT back with a bare rusqlite connection -- this must
    // be exactly what GRDB's `DateFormatter` would have produced
    // ("yyyy-MM-dd HH:mm:ss.SSS", UTC, always 3 fractional digits), so a
    // real Swift `SessionDatabase` opening this same file would decode it
    // identically.
    let conn = rusqlite::Connection::open(&path).unwrap();
    let raw: String = conn
        .query_row(
            "SELECT addedAt FROM session WHERE id = '66666666-6666-6666-6666-666666666666'",
            [],
            |row| row.get(0),
        )
        .unwrap();
    assert_eq!(raw, "2027-03-04 05:06:07.042");

    // And reopening through our own port reads it back identically.
    let db2 = SessionDatabase::open(&path).unwrap();
    let reread = db2
        .all_sessions()
        .unwrap()
        .into_iter()
        .find(|s| s.id == "66666666-6666-6666-6666-666666666666")
        .unwrap();
    assert_eq!(reread, record);
}

#[test]
fn upsert_on_existing_fixture_row_updates_not_duplicates() {
    let (db, _dir) = open_fixture_copy("upsert_update");
    let mut updated = expected_sessions()[0].clone();
    updated.name = "改名後".to_string();
    updated.sort_order = 100;
    db.upsert(&updated).unwrap();

    let all = db.all_sessions().unwrap();
    assert_eq!(
        all.len(),
        4,
        "upsert on an existing id must update, not insert a 5th row"
    );
    assert!(all.contains(&updated));
}

#[test]
fn delete_session_removes_exactly_one_fixture_row() {
    let (db, _dir) = open_fixture_copy("delete_session");
    db.delete_session("22222222-2222-2222-2222-222222222222")
        .unwrap();
    let remaining: Vec<String> = db
        .all_sessions()
        .unwrap()
        .into_iter()
        .map(|s| s.id)
        .collect();
    assert_eq!(
        remaining,
        vec![
            "11111111-1111-1111-1111-111111111111",
            "33333333-3333-3333-3333-333333333333",
            "44444444-4444-4444-4444-444444444444",
        ]
    );
}

/// Exercises `SessionDatabase` purely through the `SessionPersisting`
/// trait object -- the interface call sites are meant to depend on (see
/// `store::persisting`'s doc comment) -- to confirm the trait impl actually
/// wires up to the same fixture-backed behavior as the inherent methods
/// used by every other test in this file.
#[test]
fn all_8_operations_are_reachable_through_the_session_persisting_trait() {
    let (db, _dir) = open_fixture_copy("via_trait");
    let persisting: &dyn SessionPersisting = &db;

    assert_eq!(persisting.all_sessions().unwrap(), expected_sessions());
    assert_eq!(
        persisting.selected_session_id().unwrap(),
        Some("11111111-1111-1111-1111-111111111111".to_string())
    );
    assert_eq!(
        persisting.app_state("other.unrelated.key").unwrap(),
        Some("unrelated-value".to_string())
    );
    assert_eq!(
        persisting
            .app_state_entries("tab.pane.layout.")
            .unwrap()
            .len(),
        3
    );

    persisting.set_app_state(Some("v"), "trait.key").unwrap();
    assert_eq!(
        persisting.app_state("trait.key").unwrap(),
        Some("v".to_string())
    );

    persisting
        .set_selected_session_id(Some("22222222-2222-2222-2222-222222222222"))
        .unwrap();
    assert_eq!(
        persisting.selected_session_id().unwrap(),
        Some("22222222-2222-2222-2222-222222222222".to_string())
    );

    let record = SessionRecord::new(
        "77777777-7777-7777-7777-777777777777",
        "/tmp/seven",
        "seven",
        None,
        utc(2027, 1, 1, 0, 0, 0, 0),
        50,
        None,
        None,
        None,
    );
    persisting.upsert(&record).unwrap();
    assert!(persisting.all_sessions().unwrap().contains(&record));
    persisting.delete_session(&record.id).unwrap();
    assert!(!persisting
        .all_sessions()
        .unwrap()
        .iter()
        .any(|s| s.id == record.id));
}

fn raw_grdb_migrations(path: &Path) -> Vec<String> {
    let conn = rusqlite::Connection::open(path).unwrap();
    let mut stmt = conn
        .prepare("SELECT identifier FROM grdb_migrations ORDER BY identifier")
        .unwrap();
    stmt.query_map([], |row| row.get::<_, String>(0))
        .unwrap()
        .collect::<Result<Vec<_>, _>>()
        .unwrap()
}
